export const LOGIN_METAMASK_START = "LOGIN_START";
export const LOGIN_METAMASK_SUCCESS = "LOGIN_METAMASK_SUCCESS";
export const LOGIN_METAMASK_FAIL = "LOGIN_METAMASK_FAIL";
export const REFRESH_ERROR_STATE = "REFRESH_ERROR_STATE";
